apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mee-islyna6653-rotanakkosal-next-ingress
  namespace: mee-islyna6653-rotanakkosal-next
  annotation:
spec:
  ingressClassName: nginx
  rules:
  - host: next-v21.tinhlgkiddy.fun
    http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: mee-islyna6653-rotanakkosal-next-service 
            port:
              number: 8232
